const SONGS = [
  {
    name: "M_TURKWAZ_02",
    url: "./sounds/MUSIC/M_TURKWAZ_02.mp3",
    duration: 395,
    tags: ["music"],
    credit: "./sounds/XX_OUTRO/NAMES/TURKWAZ.mp3",
  },
  {
    name: "M_TURKWAZ_03",
    url: "./sounds/MUSIC/M_TURKWAZ_03.mp3",
    duration: 319,
    tags: ["music"],
    credit: "./sounds/XX_OUTRO/NAMES/TURKWAZ.mp3",
  },
  {
    name: "M_TURKWAZ_01",
    url: "./sounds/MUSIC/M_TURKWAZ_01.mp3",
    duration: 384,
    tags: ["music"],
    credit: "./sounds/XX_OUTRO/NAMES/TURKWAZ.mp3",
  },
  {
    name: "M_TURKWAZ_04",
    url: "./sounds/MUSIC/M_TURKWAZ_04.mp3",
    duration: 111,
    tags: ["music"],
    credit: "./sounds/XX_OUTRO/NAMES/TURKWAZ.mp3",
  },
  {
    name: "M_TURKWAZ_10",
    url: "./sounds/MUSIC/M_TURKWAZ_10.mp3",
    duration: 160,
    tags: ["music"],
    credit: "./sounds/XX_OUTRO/NAMES/TURKWAZ.mp3",
  },
  {
    name: "M_DEMI_08",
    url: "./sounds/MUSIC/M_DEMI_08.mp3",
    duration: 75,
    tags: ["music"],
    credit: "",
  },
  {
    name: "M_TURKWAZ_05",
    url: "./sounds/MUSIC/M_TURKWAZ_05.mp3",
    duration: 247,
    tags: ["music"],
    credit: "./sounds/XX_OUTRO/NAMES/TURKWAZ.mp3",
  },
  {
    name: "M_KIKO_B_03",
    url: "./sounds/MUSIC/M_KIKO_B_03.mp3",
    duration: 113,
    tags: ["music"],
    credit: "./sounds/XX_OUTRO/NAMES/KIKO.mp3",
  },
  {
    name: "M_KIKO_Z_02",
    url: "./sounds/MUSIC/M_KIKO_Z_02.mp3",
    duration: 158,
    tags: ["music"],
    credit: "./sounds/XX_OUTRO/NAMES/KIKO.mp3",
  },
  {
    name: "M_KIKO_B_02",
    url: "./sounds/MUSIC/M_KIKO_B_02.mp3",
    duration: 148,
    tags: ["music"],
    credit: "./sounds/XX_OUTRO/NAMES/KIKO.mp3",
  },
  {
    name: "M_KIKO_Z_01",
    url: "./sounds/MUSIC/M_KIKO_Z_01.mp3",
    duration: 77,
    tags: ["music"],
    credit: "./sounds/XX_OUTRO/NAMES/KIKO.mp3",
  },
  {
    name: "M_KIKO_B_01",
    url: "./sounds/MUSIC/M_KIKO_B_01.mp3",
    duration: 162,
    tags: ["music"],
    credit: "./sounds/XX_OUTRO/NAMES/KIKO.mp3",
  },
  {
    name: "M_KIKO_S_02",
    url: "./sounds/MUSIC/M_KIKO_S_02.mp3",
    duration: 63,
    tags: ["music"],
    credit: "./sounds/XX_OUTRO/NAMES/KIKO.mp3",
  },
  {
    name: "M_DEMI_13",
    url: "./sounds/MUSIC/M_DEMI_13.mp3",
    duration: 102,
    tags: ["music"],
    credit: "",
  },
  {
    name: "M_DEMI_06",
    url: "./sounds/MUSIC/M_DEMI_06.mp3",
    duration: 111,
    tags: ["music"],
    credit: "",
  },
  {
    name: "M_CHARLOTTE_16",
    url: "./sounds/MUSIC/M_CHARLOTTE_16.mp3",
    duration: 68,
    tags: ["music"],
    credit: "./sounds/XX_OUTRO/NAMES/CHARLOTTE.mp3",
  },
  {
    name: "M_CHARLOTTE_14",
    url: "./sounds/MUSIC/M_CHARLOTTE_14.mp3",
    duration: 76,
    tags: ["music"],
    credit: "./sounds/XX_OUTRO/NAMES/CHARLOTTE.mp3",
  },
  {
    name: "M_DEMI_11",
    url: "./sounds/MUSIC/M_DEMI_11.mp3",
    duration: 87,
    tags: ["music"],
    credit: "",
  },
  {
    name: "M_DEMI_05",
    url: "./sounds/MUSIC/M_DEMI_05.mp3",
    duration: 34,
    tags: ["music"],
    credit: "",
  },
  {
    name: "M_TURKWAZ_09",
    url: "./sounds/MUSIC/M_TURKWAZ_09.mp3",
    duration: 241,
    tags: ["music"],
    credit: "./sounds/XX_OUTRO/NAMES/TURKWAZ.mp3",
  },
  {
    name: "M_CHARLOTTE_15",
    url: "./sounds/MUSIC/M_CHARLOTTE_15.mp3",
    duration: 60,
    tags: ["music"],
    credit: "./sounds/XX_OUTRO/NAMES/CHARLOTTE.mp3",
  },
  {
    name: "M_CHARLOTTE_11",
    url: "./sounds/MUSIC/M_CHARLOTTE_11.mp3",
    duration: 94,
    tags: ["music"],
    credit: "./sounds/XX_OUTRO/NAMES/CHARLOTTE.mp3",
  },
  {
    name: "M_KIKO_C_06",
    url: "./sounds/MUSIC/M_KIKO_C_06.mp3",
    duration: 79,
    tags: ["music"],
    credit: "./sounds/XX_OUTRO/NAMES/KIKO.mp3",
  },
  {
    name: "M_CHARLOTTE_10",
    url: "./sounds/MUSIC/M_CHARLOTTE_10.mp3",
    duration: 130,
    tags: ["music"],
    credit: "./sounds/XX_OUTRO/NAMES/CHARLOTTE.mp3",
  },
  {
    name: "M_CHARLOTTE_12",
    url: "./sounds/MUSIC/M_CHARLOTTE_12.mp3",
    duration: 141,
    tags: ["music"],
    credit: "./sounds/XX_OUTRO/NAMES/CHARLOTTE.mp3",
  },
  {
    name: "M_DEMI_02",
    url: "./sounds/MUSIC/M_DEMI_02.mp3",
    duration: 45,
    tags: ["music"],
    credit: "",
  },
  {
    name: "M_DEMI_03",
    url: "./sounds/MUSIC/M_DEMI_03.mp3",
    duration: 42,
    tags: ["music"],
    credit: "",
  },
  {
    name: "M_CHARLOTTE_13",
    url: "./sounds/MUSIC/M_CHARLOTTE_13.mp3",
    duration: 146,
    tags: ["music"],
    credit: "./sounds/XX_OUTRO/NAMES/CHARLOTTE.mp3",
  },
  {
    name: "M_KIKO_C_05",
    url: "./sounds/MUSIC/M_KIKO_C_05.mp3",
    duration: 61,
    tags: ["music"],
    credit: "./sounds/XX_OUTRO/NAMES/KIKO.mp3",
  },
  {
    name: "P_ALBERT_15",
    url: "./sounds/POETRY/P_ALBERT_15.mp3",
    duration: 110,
    tags: ["poetry"],
    credit: "./sounds/XX_OUTRO/NAMES/ALBERT.mp3",
  },
  {
    name: "P_ALBERT_01",
    url: "./sounds/POETRY/P_ALBERT_01.mp3",
    duration: 57,
    tags: ["poetry"],
    credit: "./sounds/XX_OUTRO/NAMES/ALBERT.mp3",
  },
  {
    name: "P_ALBERT_14",
    url: "./sounds/POETRY/P_ALBERT_14.mp3",
    duration: 127,
    tags: ["poetry"],
    credit: "./sounds/XX_OUTRO/NAMES/ALBERT.mp3",
  },
  {
    name: "P_ALBERT_02",
    url: "./sounds/POETRY/P_ALBERT_02.mp3",
    duration: 268,
    tags: ["poetry"],
    credit: "./sounds/XX_OUTRO/NAMES/ALBERT.mp3",
  },
  {
    name: "P_ALBERT_16",
    url: "./sounds/POETRY/P_ALBERT_16.mp3",
    duration: 27,
    tags: ["poetry"],
    credit: "./sounds/XX_OUTRO/NAMES/ALBERT.mp3",
  },
  {
    name: "P_ALBERT_17",
    url: "./sounds/POETRY/P_ALBERT_17.mp3",
    duration: 62,
    tags: ["poetry"],
    credit: "./sounds/XX_OUTRO/NAMES/ALBERT.mp3",
  },
  {
    name: "P_ALBERT_03",
    url: "./sounds/POETRY/P_ALBERT_03.mp3",
    duration: 41,
    tags: ["poetry"],
    credit: "./sounds/XX_OUTRO/NAMES/ALBERT.mp3",
  },
  {
    name: "P_ALBERT_07",
    url: "./sounds/POETRY/P_ALBERT_07.mp3",
    duration: 36,
    tags: ["poetry"],
    credit: "./sounds/XX_OUTRO/NAMES/ALBERT.mp3",
  },
  {
    name: "P_ALBERT_13",
    url: "./sounds/POETRY/P_ALBERT_13.mp3",
    duration: 73,
    tags: ["poetry"],
    credit: "./sounds/XX_OUTRO/NAMES/ALBERT.mp3",
  },
  {
    name: "P_ALBERT_12",
    url: "./sounds/POETRY/P_ALBERT_12.mp3",
    duration: 48,
    tags: ["poetry"],
    credit: "./sounds/XX_OUTRO/NAMES/ALBERT.mp3",
  },
  {
    name: "P_ALBERT_06",
    url: "./sounds/POETRY/P_ALBERT_06.mp3",
    duration: 45,
    tags: ["poetry"],
    credit: "./sounds/XX_OUTRO/NAMES/ALBERT.mp3",
  },
  {
    name: "P_ALBERT_10",
    url: "./sounds/POETRY/P_ALBERT_10.mp3",
    duration: 23,
    tags: ["poetry"],
    credit: "./sounds/XX_OUTRO/NAMES/ALBERT.mp3",
  },
  {
    name: "P_ALBERT_04",
    url: "./sounds/POETRY/P_ALBERT_04.mp3",
    duration: 53,
    tags: ["poetry"],
    credit: "./sounds/XX_OUTRO/NAMES/ALBERT.mp3",
  },
  {
    name: "P_ALBERT_05",
    url: "./sounds/POETRY/P_ALBERT_05.mp3",
    duration: 38,
    tags: ["poetry"],
    credit: "./sounds/XX_OUTRO/NAMES/ALBERT.mp3",
  },
  {
    name: "P_ALBERT_11",
    url: "./sounds/POETRY/P_ALBERT_11.mp3",
    duration: 89,
    tags: ["poetry"],
    credit: "./sounds/XX_OUTRO/NAMES/ALBERT.mp3",
  },
  {
    name: "P_ALBERT_08",
    url: "./sounds/POETRY/P_ALBERT_08.mp3",
    duration: 49,
    tags: ["poetry"],
    credit: "./sounds/XX_OUTRO/NAMES/ALBERT.mp3",
  },
  {
    name: "P_NAMITHA_03",
    url: "./sounds/POETRY/P_NAMITHA_03.mp3",
    duration: 30,
    tags: ["poetry"],
    credit: "./sounds/XX_OUTRO/NAMES/NAMITHA.mp3",
  },
  {
    name: "P_NAMITHA_02",
    url: "./sounds/POETRY/P_NAMITHA_02.mp3",
    duration: 55,
    tags: ["poetry"],
    credit: "./sounds/XX_OUTRO/NAMES/NAMITHA.mp3",
  },
  {
    name: "P_ALBERT_09",
    url: "./sounds/POETRY/P_ALBERT_09.mp3",
    duration: 36,
    tags: ["poetry"],
    credit: "./sounds/XX_OUTRO/NAMES/ALBERT.mp3",
  },
  {
    name: "P_NAMITHA_01",
    url: "./sounds/POETRY/P_NAMITHA_01.mp3",
    duration: 47,
    tags: ["poetry"],
    credit: "./sounds/XX_OUTRO/NAMES/NAMITHA.mp3",
  },
  {
    name: "P_NAMITHA_05",
    url: "./sounds/POETRY/P_NAMITHA_05.mp3",
    duration: 29,
    tags: ["poetry"],
    credit: "./sounds/XX_OUTRO/NAMES/NAMITHA.mp3",
  },
  {
    name: "P_NAMITHA_04",
    url: "./sounds/POETRY/P_NAMITHA_04.mp3",
    duration: 26,
    tags: ["poetry"],
    credit: "./sounds/XX_OUTRO/NAMES/NAMITHA.mp3",
  },
  {
    name: "P_NAMITHA_06",
    url: "./sounds/POETRY/P_NAMITHA_06.mp3",
    duration: 11,
    tags: ["poetry"],
    credit: "./sounds/XX_OUTRO/NAMES/NAMITHA.mp3",
  },
  {
    name: "P_ALBERT_18",
    url: "./sounds/POETRY/P_ALBERT_18.mp3",
    duration: 64,
    tags: ["poetry"],
    credit: "./sounds/XX_OUTRO/NAMES/ALBERT.mp3",
  },
  {
    name: "S_KIKO_S_04",
    url: "./sounds/SHORTS/S_KIKO_S_04.mp3",
    duration: 36,
    tags: ["shorts"],
    credit: "./sounds/XX_OUTRO/NAMES/KIKO.mp3",
  },
  {
    name: "S_KIKO_S_03",
    url: "./sounds/SHORTS/S_KIKO_S_03.mp3",
    duration: 36,
    tags: ["shorts"],
    credit: "./sounds/XX_OUTRO/NAMES/KIKO.mp3",
  },
  {
    name: "S_KIKO_S_02",
    url: "./sounds/SHORTS/S_KIKO_S_02.mp3",
    duration: 28,
    tags: ["shorts"],
    credit: "./sounds/XX_OUTRO/NAMES/KIKO.mp3",
  },
  {
    name: "S_BIRDS_17",
    url: "./sounds/SHORTS/S_BIRDS_17.mp3",
    duration: 64,
    tags: ["shorts"],
    credit: "",
  },
  {
    name: "S_BIRDS_03",
    url: "./sounds/SHORTS/S_BIRDS_03.mp3",
    duration: 71,
    tags: ["shorts"],
    credit: "",
  },
  {
    name: "S_DEMI_16",
    url: "./sounds/SHORTS/S_DEMI_16.mp3",
    duration: 22,
    tags: ["shorts"],
    credit: "",
  },
  {
    name: "S_KIKO_C_01",
    url: "./sounds/SHORTS/S_KIKO_C_01.mp3",
    duration: 54,
    tags: ["shorts"],
    credit: "./sounds/XX_OUTRO/NAMES/KIKO.mp3",
  },
  {
    name: "S_DEMI_17",
    url: "./sounds/SHORTS/S_DEMI_17.mp3",
    duration: 11,
    tags: ["shorts"],
    credit: "",
  },
  {
    name: "S_CHARLOTTE_09",
    url: "./sounds/SHORTS/S_CHARLOTTE_09.mp3",
    duration: 22,
    tags: ["shorts"],
    credit: "./sounds/XX_OUTRO/NAMES/CHARLOTTE.mp3",
  },
  {
    name: "S_BIRDS_02",
    url: "./sounds/SHORTS/S_BIRDS_02.mp3",
    duration: 84,
    tags: ["shorts"],
    credit: "",
  },
  {
    name: "S_BIRDS_16",
    url: "./sounds/SHORTS/S_BIRDS_16.mp3",
    duration: 32,
    tags: ["shorts"],
    credit: "",
  },
  {
    name: "S_BIRDS_14",
    url: "./sounds/SHORTS/S_BIRDS_14.mp3",
    duration: 73,
    tags: ["shorts"],
    credit: "",
  },
  {
    name: "S_DEMI_15",
    url: "./sounds/SHORTS/S_DEMI_15.mp3",
    duration: 10,
    tags: ["shorts"],
    credit: "",
  },
  {
    name: "S_KIKO_C_02",
    url: "./sounds/SHORTS/S_KIKO_C_02.mp3",
    duration: 37,
    tags: ["shorts"],
    credit: "./sounds/XX_OUTRO/NAMES/KIKO.mp3",
  },
  {
    name: "S_DEMI_14",
    url: "./sounds/SHORTS/S_DEMI_14.mp3",
    duration: 14,
    tags: ["shorts"],
    credit: "",
  },
  {
    name: "S_BIRDS_15",
    url: "./sounds/SHORTS/S_BIRDS_15.mp3",
    duration: 35,
    tags: ["shorts"],
    credit: "",
  },
  {
    name: "S_BIRDS_01",
    url: "./sounds/SHORTS/S_BIRDS_01.mp3",
    duration: 96,
    tags: ["shorts"],
    credit: "",
  },
  {
    name: "S_BIRDS_05",
    url: "./sounds/SHORTS/S_BIRDS_05.mp3",
    duration: 66,
    tags: ["shorts"],
    credit: "",
  },
  {
    name: "S_BIRDS_11",
    url: "./sounds/SHORTS/S_BIRDS_11.mp3",
    duration: 41,
    tags: ["shorts"],
    credit: "",
  },
  {
    name: "S_BIRDS_10",
    url: "./sounds/SHORTS/S_BIRDS_10.mp3",
    duration: 65,
    tags: ["shorts"],
    credit: "",
  },
  {
    name: "S_BIRDS_04",
    url: "./sounds/SHORTS/S_BIRDS_04.mp3",
    duration: 60,
    tags: ["shorts"],
    credit: "",
  },
  {
    name: "S_BIRDS_12",
    url: "./sounds/SHORTS/S_BIRDS_12.mp3",
    duration: 31,
    tags: ["shorts"],
    credit: "",
  },
  {
    name: "S_BIRDS_06",
    url: "./sounds/SHORTS/S_BIRDS_06.mp3",
    duration: 88,
    tags: ["shorts"],
    credit: "",
  },
  {
    name: "S_BIRDS_07",
    url: "./sounds/SHORTS/S_BIRDS_07.mp3",
    duration: 92,
    tags: ["shorts"],
    credit: "",
  },
  {
    name: "S_BIRDS_13",
    url: "./sounds/SHORTS/S_BIRDS_13.mp3",
    duration: 56,
    tags: ["shorts"],
    credit: "",
  },
  {
    name: "S_DEMI_23",
    url: "./sounds/SHORTS/S_DEMI_23.mp3",
    duration: 21,
    tags: ["shorts"],
    credit: "",
  },
  {
    name: "S_CHARLOTTE_01",
    url: "./sounds/SHORTS/S_CHARLOTTE_01.mp3",
    duration: 74,
    tags: ["shorts"],
    credit: "./sounds/XX_OUTRO/NAMES/CHARLOTTE.mp3",
  },
  {
    name: "S_KIKO_C_09",
    url: "./sounds/SHORTS/S_KIKO_C_09.mp3",
    duration: 41,
    tags: ["shorts"],
    credit: "./sounds/XX_OUTRO/NAMES/KIKO.mp3",
  },
  {
    name: "S_DEMI_22",
    url: "./sounds/SHORTS/S_DEMI_22.mp3",
    duration: 22,
    tags: ["shorts"],
    credit: "",
  },
  {
    name: "S_LAUGHING_01",
    url: "./sounds/SHORTS/S_LAUGHING_01.mp3",
    duration: 15,
    tags: ["shorts"],
    credit: "",
  },
  {
    name: "S_BIRDS_09",
    url: "./sounds/SHORTS/S_BIRDS_09.mp3",
    duration: 46,
    tags: ["shorts"],
    credit: "",
  },
  {
    name: "S_DEMI_20",
    url: "./sounds/SHORTS/S_DEMI_20.mp3",
    duration: 22,
    tags: ["shorts"],
    credit: "",
  },
  {
    name: "S_CHARLOTTE_02",
    url: "./sounds/SHORTS/S_CHARLOTTE_02.mp3",
    duration: 25,
    tags: ["shorts"],
    credit: "./sounds/XX_OUTRO/NAMES/CHARLOTTE.mp3",
  },
  {
    name: "S_CHARLOTTE_03",
    url: "./sounds/SHORTS/S_CHARLOTTE_03.mp3",
    duration: 31,
    tags: ["shorts"],
    credit: "./sounds/XX_OUTRO/NAMES/CHARLOTTE.mp3",
  },
  {
    name: "S_DEMI_21",
    url: "./sounds/SHORTS/S_DEMI_21.mp3",
    duration: 10,
    tags: ["shorts"],
    credit: "",
  },
  {
    name: "S_LAUGHING_02",
    url: "./sounds/SHORTS/S_LAUGHING_02.mp3",
    duration: 28,
    tags: ["shorts"],
    credit: "",
  },
  {
    name: "S_BIRDS_08",
    url: "./sounds/SHORTS/S_BIRDS_08.mp3",
    duration: 57,
    tags: ["shorts"],
    credit: "",
  },
  {
    name: "S_BIRDS_18",
    url: "./sounds/SHORTS/S_BIRDS_18.mp3",
    duration: 63,
    tags: ["shorts"],
    credit: "",
  },
  {
    name: "S_CHARLOTTE_07",
    url: "./sounds/SHORTS/S_CHARLOTTE_07.mp3",
    duration: 41,
    tags: ["shorts"],
    credit: "./sounds/XX_OUTRO/NAMES/CHARLOTTE.mp3",
  },
  {
    name: "S_DEMI_19",
    url: "./sounds/SHORTS/S_DEMI_19.mp3",
    duration: 15,
    tags: ["shorts"],
    credit: "",
  },
  {
    name: "S_DEMI_18",
    url: "./sounds/SHORTS/S_DEMI_18.mp3",
    duration: 21,
    tags: ["shorts"],
    credit: "",
  },
  {
    name: "S_KIKO_B_04",
    url: "./sounds/SHORTS/S_KIKO_B_04.mp3",
    duration: 21,
    tags: ["shorts"],
    credit: "./sounds/XX_OUTRO/NAMES/KIKO.mp3",
  },
  {
    name: "I_JAYNE_02",
    url: "./sounds/INTERVIEWS/I_JAYNE_02.mp3",
    duration: 79,
    tags: ["interviews"],
    credit: "",
  },
  {
    name: "I_JAYNE_03",
    url: "./sounds/INTERVIEWS/I_JAYNE_03.mp3",
    duration: 149,
    tags: ["interviews"],
    credit: "",
  },
  {
    name: "I_JAYNE_01",
    url: "./sounds/INTERVIEWS/I_JAYNE_01.mp3",
    duration: 226,
    tags: ["interviews"],
    credit: "",
  },
  {
    name: "I_LOUELLA_02",
    url: "./sounds/INTERVIEWS/I_LOUELLA_02.mp3",
    duration: 140,
    tags: ["interviews"],
    credit: "./sounds/XX_OUTRO/NAMES/LOUELLA.mp3",
  },
  {
    name: "I_ELLEN_02_TempMusic",
    url: "./sounds/INTERVIEWS/I_ELLEN_02_TempMusic.mp3",
    duration: 133,
    tags: ["interviews"],
    credit: "./sounds/XX_OUTRO/NAMES/ELLEN.mp3",
  },
  {
    name: "I_LOUELLA_03",
    url: "./sounds/INTERVIEWS/I_LOUELLA_03.mp3",
    duration: 198,
    tags: ["interviews"],
    credit: "./sounds/XX_OUTRO/NAMES/LOUELLA.mp3",
  },
  {
    name: "I_LOUELLA_01",
    url: "./sounds/INTERVIEWS/I_LOUELLA_01.mp3",
    duration: 237,
    tags: ["interviews"],
    credit: "./sounds/XX_OUTRO/NAMES/LOUELLA.mp3",
  },
  {
    name: "I_KIKO_02",
    url: "./sounds/INTERVIEWS/I_KIKO_02.mp3",
    duration: 247,
    tags: ["interviews"],
    credit: "./sounds/XX_OUTRO/NAMES/KIKO.mp3",
  },
  {
    name: "I_KIKO_03",
    url: "./sounds/INTERVIEWS/I_KIKO_03.mp3",
    duration: 174,
    tags: ["interviews"],
    credit: "./sounds/XX_OUTRO/NAMES/KIKO.mp3",
  },
  {
    name: "I_KIKO_01",
    url: "./sounds/INTERVIEWS/I_KIKO_01.mp3",
    duration: 233,
    tags: ["interviews"],
    credit: "./sounds/XX_OUTRO/NAMES/KIKO.mp3",
  },
  {
    name: "I_ELLEN_01_TempMusic",
    url: "./sounds/INTERVIEWS/I_ELLEN_01_TempMusic.mp3",
    duration: 172,
    tags: ["interviews"],
    credit: "./sounds/XX_OUTRO/NAMES/ELLEN.mp3",
  },
  {
    name: "I_JESSE_01",
    url: "./sounds/INTERVIEWS/I_JESSE_01.mp3",
    duration: 229,
    tags: ["interviews"],
    credit: "./sounds/XX_OUTRO/NAMES/JESSE.mp3",
  },
  {
    name: "I_ELLEN_03",
    url: "./sounds/INTERVIEWS/I_ELLEN_03.mp3",
    duration: 244,
    tags: ["interviews"],
    credit: "./sounds/XX_OUTRO/NAMES/ELLEN.mp3",
  },
  {
    name: "I_SAM_01",
    url: "./sounds/INTERVIEWS/I_SAM_01.mp3",
    duration: 137,
    tags: ["interviews"],
    credit: "./sounds/XX_OUTRO/NAMES/SAM.mp3",
  },
  {
    name: "I_ELLEN_04",
    url: "./sounds/INTERVIEWS/I_ELLEN_04.mp3",
    duration: 154,
    tags: ["interviews"],
    credit: "./sounds/XX_OUTRO/NAMES/ELLEN.mp3",
  },
  {
    name: "I_ELLEN_05",
    url: "./sounds/INTERVIEWS/I_ELLEN_05.mp3",
    duration: 151,
    tags: ["interviews"],
    credit: "./sounds/XX_OUTRO/NAMES/ELLEN.mp3",
  },
].map((song) => {
  song.audio = createAudioElement(song.url);
  return song;
});
