window.SONGSRAW = [

{
  name: "INTRO_2",
  url: "./sounds/00_INTRO/INTRO_2.mp3",
  duration: 113,
  author: "",
  form: "",
  placement: [""],
  length: "",
  language: "",
  sentiment: "",
  tags: ["intro"],
  backgroundMusic: "",
  credit: "",
},
// {
//   name: "OUTRO_2.2",
//   url: "./sounds/XX_OUTRO/OUTRO_2.2.mp3",
//   duration: 6,
//   author: "",
//   form: "",
//   placement: [""],
//   length: "",
//   language: "",
//   sentiment: "",
//   tags: ["outro"],
//   backgroundMusic: "",
//   credit: "",
// },
{
  name: "M_CHARLOTTE_10",
  url: "./sounds/MUSIC/M_CHARLOTTE_10.mp3",
  duration: 130,
  author: "CHARLOTTE",
  form: "music",
  placement: ["middle", "end"],
  length: "medium",
  language: "verbal",
  sentiment: "moderate",
  tags: ["Home", "wellness", "nature"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_CHARLOTTE.mp3",
},
{
  name: "M_CHARLOTTE_11",
  url: "./sounds/MUSIC/M_CHARLOTTE_11.mp3",
  duration: 95,
  author: "CHARLOTTE",
  form: "music",
  placement: ["middle", "end"],
  length: "short",
  language: "verbal",
  sentiment: "moderate",
  tags: ["sound", "home"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_CHARLOTTE.mp3",
},
{
  name: "M_CHARLOTTE_12",
  url: "./sounds/MUSIC/M_CHARLOTTE_12.mp3",
  duration: 142,
  author: "CHARLOTTE",
  form: "music",
  placement: ["middle", "end"],
  length: "medium",
  language: "verbal",
  sentiment: "moderate",
  tags: ["Home"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_CHARLOTTE.mp3",
},
{
  name: "M_CHARLOTTE_13",
  url: "./sounds/MUSIC/M_CHARLOTTE_13.mp3",
  duration: 147,
  author: "CHARLOTTE",
  form: "music",
  placement: ["middle", "end"],
  length: "medium",
  language: "verbal",
  sentiment: "moderate",
  tags: ["wellness"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_CHARLOTTE.mp3",
},
{
  name: "M_CHARLOTTE_14",
  url: "./sounds/MUSIC/M_CHARLOTTE_14.mp3",
  duration: 76,
  author: "CHARLOTTE",
  form: "music",
  placement: ["middle", "end"],
  length: "medium",
  language: "verbal",
  sentiment: "moderate",
  tags: ["wellness", "nature"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_CHARLOTTE.mp3",
},
{
  name: "M_CHARLOTTE_15",
  url: "./sounds/MUSIC/M_CHARLOTTE_15.mp3",
  duration: 61,
  author: "CHARLOTTE",
  form: "music",
  placement: ["end"],
  length: "short",
  language: "verbal",
  sentiment: "moderate",
  tags: ["Home", "nature"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_CHARLOTTE.mp3",
},
{
  name: "M_CHARLOTTE_16",
  url: "./sounds/MUSIC/M_CHARLOTTE_16.mp3",
  duration: 68,
  author: "CHARLOTTE",
  form: "music",
  placement: ["end", "middle"],
  length: "medium",
  language: "verbal",
  sentiment: "moderate",
  tags: ["wellness", "Home", "nature"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_CHARLOTTE.mp3",
},
{
  name: "M_KIKO_B_01",
  url: "./sounds/MUSIC/M_KIKO_B_01.mp3",
  duration: 163,
  author: "KIKO",
  form: "music",
  placement: ["middle"],
  length: "medium",
  language: "nonVerbal",
  sentiment: "moderate",
  tags: ["sound", "wellness"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_KIKO.mp3",
},
{
  name: "M_KIKO_B_02",
  url: "./sounds/MUSIC/M_KIKO_B_02.mp3",
  duration: 149,
  author: "KIKO",
  form: "music",
  placement: ["middle"],
  length: "medium",
  language: "nonVerbal",
  sentiment: "moderate",
  tags: ["sound", "wellness"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_KIKO.mp3",
},
{
  name: "M_KIKO_B_03",
  url: "./sounds/MUSIC/M_KIKO_B_03.mp3",
  duration: 114,
  author: "KIKO",
  form: "music",
  placement: ["middle"],
  length: "medium",
  language: "nonVerbal",
  sentiment: "moderate",
  tags: ["sound", "wellness"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_KIKO.mp3",
},
{
  name: "M_KIKO_C_05",
  url: "./sounds/MUSIC/M_KIKO_C_05.mp3",
  duration: 61,
  author: "KIKO",
  form: "music",
  placement: ["middle"],
  length: "medium",
  language: "nonVerbal",
  sentiment: "moderate",
  tags: ["sound", "wellness"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_KIKO.mp3",
},
{
  name: "M_KIKO_C_06",
  url: "./sounds/MUSIC/M_KIKO_C_06.mp3",
  duration: 80,
  author: "KIKO",
  form: "music",
  placement: ["middle"],
  length: "medium",
  language: "nonVerbal",
  sentiment: "moderate",
  tags: ["sound", "wellness"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_KIKO.mp3",
},
{
  name: "M_KIKO_S_02",
  url: "./sounds/MUSIC/M_KIKO_S_02.mp3",
  duration: 64,
  author: "KIKO",
  form: "music",
  placement: ["middle"],
  length: "medium",
  language: "nonVerbal",
  sentiment: "moderate",
  tags: ["sound", "wellness"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_KIKO.mp3",
},
{
  name: "M_KIKO_Z_01",
  url: "./sounds/MUSIC/M_KIKO_Z_01.mp3",
  duration: 77,
  author: "KIKO",
  form: "music",
  placement: ["middle"],
  length: "medium",
  language: "nonVerbal",
  sentiment: "moderate",
  tags: ["sound", "wellness"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_KIKO.mp3",
},
{
  name: "M_KIKO_Z_02",
  url: "./sounds/MUSIC/M_KIKO_Z_02.mp3",
  duration: 158,
  author: "KIKO",
  form: "music",
  placement: ["middle"],
  length: "medium",
  language: "nonVerbal",
  sentiment: "moderate",
  tags: ["sound", "wellness"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_KIKO.mp3",
},
{
  name: "M_DEMI_02",
  url: "./sounds/MUSIC/M_DEMI_02.mp3",
  duration: 46,
  author: "DEMETRI",
  form: "music",
  placement: ["middle"],
  length: "short",
  language: "nonVerbal",
  sentiment: "moderate",
  tags: ["sound", "home"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_DEMETRI.mp3",
},
{
  name: "M_DEMI_03",
  url: "./sounds/MUSIC/M_DEMI_03.mp3",
  duration: 42,
  author: "DEMETRI",
  form: "music",
  placement: ["middle"],
  length: "short",
  language: "nonVerbal",
  sentiment: "moderate",
  tags: ["sound", "home"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_DEMETRI.mp3",
},
{
  name: "M_DEMI_05",
  url: "./sounds/MUSIC/M_DEMI_05.mp3",
  duration: 34,
  author: "DEMETRI",
  form: "music",
  placement: ["middle"],
  length: "short",
  language: "nonVerbal",
  sentiment: "moderate",
  tags: ["sound", "home"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_DEMETRI.mp3",
},
{
  name: "M_DEMI_06",
  url: "./sounds/MUSIC/M_DEMI_06.mp3",
  duration: 112,
  author: "DEMETRI",
  form: "music",
  placement: ["middle"],
  length: "medium",
  language: "nonVerbal",
  sentiment: "moderate",
  tags: ["sound", "home"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_DEMETRI.mp3",
},
{
  name: "M_DEMI_08",
  url: "./sounds/MUSIC/M_DEMI_08.mp3",
  duration: 75,
  author: "DEMETRI",
  form: "music",
  placement: ["middle"],
  length: "medium",
  language: "nonVerbal",
  sentiment: "moderate",
  tags: ["sound", "home"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_DEMETRI.mp3",
},
{
  name: "M_DEMI_11",
  url: "./sounds/MUSIC/M_DEMI_11.mp3",
  duration: 87,
  author: "DEMETRI",
  form: "music",
  placement: ["middle"],
  length: "medium",
  language: "verbal",
  sentiment: "moderate",
  tags: ["sound", "home"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_DEMETRI.mp3",
},
{
  name: "M_DEMI_13",
  url: "./sounds/MUSIC/M_DEMI_13.mp3",
  duration: 102,
  author: "DEMETRI",
  form: "music",
  placement: ["middle"],
  length: "medium",
  language: "nonVerbal",
  sentiment: "moderate",
  tags: ["sound", "home"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_DEMETRI.mp3",
},
{
  name: "M_TURKWAZ_01",
  url: "./sounds/MUSIC/M_TURKWAZ_01.mp3",
  duration: 384,
  author: "TURKWAZ",
  form: "music",
  placement: ["beginning", "middle", "end"],
  length: "long",
  language: "verbal",
  sentiment: "moderate",
  tags: ["sound", "home"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_TURKWAZ.mp3",
},
{
  name: "M_TURKWAZ_02",
  url: "./sounds/MUSIC/M_TURKWAZ_02.mp3",
  duration: 396,
  author: "TURKWAZ",
  form: "music",
  placement: ["middle"],
  length: "long",
  language: "verbal",
  sentiment: "moderate",
  tags: ["sound", "Home", "nature"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_TURKWAZ.mp3",
},
{
  name: "M_TURKWAZ_03",
  url: "./sounds/MUSIC/M_TURKWAZ_03.mp3",
  duration: 320,
  author: "TURKWAZ",
  form: "music",
  placement: ["middle"],
  length: "long",
  language: "verbal",
  sentiment: "heavy",
  tags: ["Nature", "Home", "wellness"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_TURKWAZ.mp3",
},
{
  name: "M_TURKWAZ_04",
  url: "./sounds/MUSIC/M_TURKWAZ_04.mp3",
  duration: 111,
  author: "TURKWAZ",
  form: "music",
  placement: ["middle"],
  length: "medium",
  language: "verbal",
  sentiment: "light",
  tags: ["sound", "nature"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_TURKWAZ.mp3",
},
{
  name: "M_TURKWAZ_05",
  url: "./sounds/MUSIC/M_TURKWAZ_05.mp3",
  duration: 248,
  author: "TURKWAZ",
  form: "music",
  placement: ["middle"],
  length: "long",
  language: "verbal",
  sentiment: "light",
  tags: ["sound", "Nature", "Home"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_TURKWAZ.mp3",
},
{
  name: "M_TURKWAZ_09",
  url: "./sounds/MUSIC/M_TURKWAZ_09.mp3",
  duration: 242,
  author: "TURKWAZ",
  form: "music",
  placement: ["middle"],
  length: "long",
  language: "verbal",
  sentiment: "light",
  tags: ["sound", "home"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_TURKWAZ.mp3",
},
{
  name: "M_TURKWAZ_10",
  url: "./sounds/MUSIC/M_TURKWAZ_10.mp3",
  duration: 160,
  author: "TURKWAZ",
  form: "music",
  placement: ["middle"],
  length: "medium",
  language: "verbal",
  sentiment: "moderate",
  tags: ["sound", "home"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_TURKWAZ.mp3",
},
{
  name: "P_ALBERT_01",
  url: "./sounds/POETRY/P_ALBERT_01.mp3",
  duration: 58,
  author: "ALBERT",
  form: "poetry",
  placement: ["middle"],
  length: "short",
  language: "verbal",
  sentiment: "heavy",
  tags: ["Nature", "Home"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_ALBERT.mp3",
},
{
  name: "P_ALBERT_02",
  url: "./sounds/POETRY/P_ALBERT_02.mp3",
  duration: 268,
  author: "ALBERT",
  form: "poetry",
  placement: ["middle"],
  length: "long",
  language: "verbal",
  sentiment: "heavy",
  tags: ["Nature", "wellness", "Home"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_ALBERT.mp3",
},
{
  name: "P_ALBERT_03",
  url: "./sounds/POETRY/P_ALBERT_03.mp3",
  duration: 42,
  author: "ALBERT",
  form: "poetry",
  placement: ["beginning", "middle", "end"],
  length: "short",
  language: "verbal",
  sentiment: "moderate",
  tags: ["wellness", "Wound", "Home"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_ALBERT.mp3",
},
{
  name: "P_ALBERT_04",
  url: "./sounds/POETRY/P_ALBERT_04.mp3",
  duration: 53,
  author: "ALBERT",
  form: "poetry",
  placement: ["middle"],
  length: "short",
  language: "verbal",
  sentiment: "heavy",
  tags: ["wellness", "Home", "Nature", "sound"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_ALBERT.mp3",
},
{
  name: "P_ALBERT_05",
  url: "./sounds/POETRY/P_ALBERT_05.mp3",
  duration: 39,
  author: "ALBERT",
  form: "poetry",
  placement: ["middle"],
  length: "short",
  language: "verbal",
  sentiment: "heavy",
  tags: ["Nature", "Home"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_ALBERT.mp3",
},
{
  name: "P_ALBERT_06",
  url: "./sounds/POETRY/P_ALBERT_06.mp3",
  duration: 45,
  author: "ALBERT",
  form: "poetry",
  placement: ["beginning, end"],
  length: "short",
  language: "verbal",
  sentiment: "heavy",
  tags: ["sound", "Home", "wellness"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_ALBERT.mp3",
},
{
  name: "P_ALBERT_07",
  url: "./sounds/POETRY/P_ALBERT_07.mp3",
  duration: 36,
  author: "ALBERT",
  form: "poetry",
  placement: ["middle"],
  length: "short",
  language: "verbal",
  sentiment: "heavy",
  tags: ["Nature", "Home", "wellness", "sound"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_ALBERT.mp3",
},
{
  name: "P_ALBERT_08",
  url: "./sounds/POETRY/P_ALBERT_08.mp3",
  duration: 49,
  author: "ALBERT",
  form: "poetry",
  placement: ["middle"],
  length: "short",
  language: "verbal",
  sentiment: "moderate",
  tags: ["Nature", "wellness"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_ALBERT.mp3",
},
{
  name: "P_ALBERT_09",
  url: "./sounds/POETRY/P_ALBERT_09.mp3",
  duration: 37,
  author: "ALBERT",
  form: "poetry",
  placement: ["middle", "end"],
  length: "short",
  language: "verbal",
  sentiment: "heavy",
  tags: ["Nature", "wellness"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_ALBERT.mp3",
},
{
  name: "P_ALBERT_10",
  url: "./sounds/POETRY/P_ALBERT_10.mp3",
  duration: 23,
  author: "ALBERT",
  form: "poetry",
  placement: ["middle"],
  length: "short",
  language: "verbal",
  sentiment: "heavy",
  tags: ["Home", "sound"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_ALBERT.mp3",
},
{
  name: "P_ALBERT_11",
  url: "./sounds/POETRY/P_ALBERT_11.mp3",
  duration: 90,
  author: "ALBERT",
  form: "poetry",
  placement: ["middle", "end"],
  length: "medium",
  language: "verbal",
  sentiment: "moderate",
  tags: ["Home", "sound", "wellness"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_ALBERT.mp3",
},
{
  name: "P_ALBERT_12",
  url: "./sounds/POETRY/P_ALBERT_12.mp3",
  duration: 48,
  author: "ALBERT",
  form: "poetry",
  placement: ["beginning", "middle"],
  length: "short",
  language: "verbal",
  sentiment: "moderate",
  tags: ["Home"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_ALBERT.mp3",
},
{
  name: "P_ALBERT_13",
  url: "./sounds/POETRY/P_ALBERT_13.mp3",
  duration: 73,
  author: "ALBERT",
  form: "poetry",
  placement: ["middle"],
  length: "medium",
  language: "verbal",
  sentiment: "moderate",
  tags: ["Nature", "wellness"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_ALBERT.mp3",
},
{
  name: "P_ALBERT_14",
  url: "./sounds/POETRY/P_ALBERT_14.mp3",
  duration: 128,
  author: "ALBERT",
  form: "poetry",
  placement: ["middle"],
  length: "medium",
  language: "verbal",
  sentiment: "heavy",
  tags: ["Nature", "Home"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_ALBERT.mp3",
},
{
  name: "P_ALBERT_15",
  url: "./sounds/POETRY/P_ALBERT_15.mp3",
  duration: 111,
  author: "ALBERT",
  form: "poetry",
  placement: ["middle"],
  length: "medium",
  language: "verbal",
  sentiment: "light, Moderate",
  tags: ["nature"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_ALBERT.mp3",
},
{
  name: "P_ALBERT_16",
  url: "./sounds/POETRY/P_ALBERT_16.mp3",
  duration: 27,
  author: "ALBERT",
  form: "poetry",
  placement: ["beginning", "middle", "end"],
  length: "short",
  language: "verbal",
  sentiment: "moderate",
  tags: ["wellness", "nature"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_ALBERT.mp3",
},
{
  name: "P_ALBERT_17",
  url: "./sounds/POETRY/P_ALBERT_17.mp3",
  duration: 62,
  author: "ALBERT",
  form: "poetry",
  placement: ["beginning", "middle", "end"],
  length: "medium",
  language: "verbal",
  sentiment: "light, Moderate",
  tags: ["Nature", "Home", "sound"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_ALBERT.mp3",
},
{
  name: "P_ALBERT_18",
  url: "./sounds/POETRY/P_ALBERT_18.mp3",
  duration: 64,
  author: "ALBERT",
  form: "poetry",
  placement: ["middle", "end"],
  length: "medium",
  language: "verbal",
  sentiment: "moderate",
  tags: ["Nature", "wellness", "Home"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_ALBERT.mp3",
},
{
  name: "P_NAMITHA_01",
  url: "./sounds/POETRY/P_NAMITHA_01.mp3",
  duration: 47,
  author: "NAMITHA",
  form: "poetry",
  placement: ["middle"],
  length: "short",
  language: "verbal",
  sentiment: "light, Moderate",
  tags: ["nature"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_NAMITHA.mp3",
},
{
  name: "P_NAMITHA_02",
  url: "./sounds/POETRY/P_NAMITHA_02.mp3",
  duration: 55,
  author: "NAMITHA",
  form: "poetry",
  placement: ["middle"],
  length: "short",
  language: "verbal",
  sentiment: "moderate",
  tags: ["Nature", "Home", "sound"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_NAMITHA.mp3",
},
{
  name: "P_NAMITHA_03",
  url: "./sounds/POETRY/P_NAMITHA_03.mp3",
  duration: 30,
  author: "NAMITHA",
  form: "poetry",
  placement: ["middle"],
  length: "short",
  language: "verbal",
  sentiment: "heavy",
  tags: ["Nature", "wellness"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_NAMITHA.mp3",
},
{
  name: "P_NAMITHA_04",
  url: "./sounds/POETRY/P_NAMITHA_04.mp3",
  duration: 26,
  author: "NAMITHA",
  form: "poetry",
  placement: ["middle"],
  length: "short",
  language: "verbal",
  sentiment: "heavy",
  tags: ["Nature", "Trees", "Home"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_NAMITHA.mp3",
},
{
  name: "P_NAMITHA_05",
  url: "./sounds/POETRY/P_NAMITHA_05.mp3",
  duration: 30,
  author: "NAMITHA",
  form: "poetry",
  placement: ["beginning", "middle"],
  length: "short",
  language: "verbal",
  sentiment: "heavy",
  tags: ["Home", "nature"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_NAMITHA.mp3",
},
{
  name: "P_NAMITHA_06",
  url: "./sounds/POETRY/P_NAMITHA_06.mp3",
  duration: 11,
  author: "NAMITHA",
  form: "poetry",
  placement: ["middle"],
  length: "short",
  language: "verbal",
  sentiment: "moderate",
  tags: ["Nature", "wellness", "sound"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_NAMITHA.mp3",
},
  {
      name: "I_ELLEN_01",
      url: "./sounds/Interview/I_ELLEN_01.mp3",
      duration: 0,
      author: "ELLEN",
      form: "interview",
      placement: ["beginning", "middle"],
      length: "medium",
      language: "verbal",
      sentiment: "light",
      tags: ["sound", "wellness", "informative"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_ELLEN.mp3",
    },
  {
      name: "I_ELLEN_02",
      url: "./sounds/Interview/I_ELLEN_02.mp3",
      duration: 0,
      author: "ELLEN",
      form: "interview",
      placement: ["middle"],
      length: "medium",
      language: "verbal",
      sentiment: "moderate",
      tags: ["sound"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_ELLEN.mp3",
    },
{
  name: "I_ELLEN_03",
  url: "./sounds/INTERVIEWS/I_ELLEN_03.mp3",
  duration: 245,
  author: "ELLEN",
  form: "interview",
  placement: ["middle"],
  length: "long",
  language: "verbal",
  sentiment: "moderate",
  tags: ["Home", "sound", "informative"],
  backgroundMusic: "DEMETRI",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_ELLEN.mp3",
},
{
  name: "I_ELLEN_04",
  url: "./sounds/INTERVIEWS/I_ELLEN_04.mp3",
  duration: 155,
  author: "ELLEN",
  form: "interview",
  placement: ["beginning", "middle", "end"],
  length: "medium",
  language: "verbal",
  sentiment: "light",
  tags: ["sound", "nature"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_ELLEN.mp3",
},
{
  name: "I_ELLEN_05",
  url: "./sounds/INTERVIEWS/I_ELLEN_05.mp3",
  duration: 151,
  author: "ELLEN",
  form: "interview",
  placement: ["beginning", "middle"],
  length: "medium",
  language: "verbal",
  sentiment: "light",
  tags: ["sound", "wellness"],
  backgroundMusic: "KIKO",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_ELLEN.mp3",
},
{
  name: "I_JAYNE_01",
  url: "./sounds/INTERVIEWS/I_JAYNE_01.mp3",
  duration: 226,
  author: "JAYNE",
  form: "interview",
  placement: ["middle"],
  length: "long",
  language: "verbal",
  sentiment: "light",
  tags: ["Nature", "sound", "informative"],
  backgroundMusic: "JESSE",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_JAYNE.mp3",
},
{
  name: "I_JAYNE_02",
  url: "./sounds/INTERVIEWS/I_JAYNE_02.mp3",
  duration: 79,
  author: "JAYNE",
  form: "interview",
  placement: ["middle"],
  length: "medium",
  language: "verbal",
  sentiment: "light",
  tags: ["Nature", "informative"],
  backgroundMusic: "DEMETRI",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_JAYNE.mp3",
},
{
  name: "I_JAYNE_03",
  url: "./sounds/INTERVIEWS/I_JAYNE_03.mp3",
  duration: 150,
  author: "JAYNE",
  form: "interview",
  placement: ["middle"],
  length: "medium",
  language: "verbal",
  sentiment: "light",
  tags: ["Nature", "sound", "informative"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_JAYNE.mp3",
},
{
  name: "I_JESSE_01",
  url: "./sounds/INTERVIEWS/I_JESSE_01.mp3",
  duration: 230,
  author: "JESSE",
  form: "interview",
  placement: ["end", "middle"],
  length: "long",
  language: "verbal",
  sentiment: "heavy",
  tags: ["sound", "Nature", "wellness", "informative"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_JESSE.mp3",
},
{
  name: "I_KIKO_01",
  url: "./sounds/INTERVIEWS/I_KIKO_01.mp3",
  duration: 233,
  author: "KIKO",
  form: "interview",
  placement: ["middle"],
  length: "long",
  language: "verbal",
  sentiment: "moderate",
  tags: ["sound", "wellness"],
  backgroundMusic: "KIKO",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_KIKO.mp3",
},
{
  name: "I_KIKO_02",
  url: "./sounds/INTERVIEWS/I_KIKO_02.mp3",
  duration: 247,
  author: "KIKO",
  form: "interview",
  placement: ["end"],
  length: "long",
  language: "verbal",
  sentiment: "heavy",
  tags: ["sound", "wellness"],
  backgroundMusic: "KIKO",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_KIKO.mp3",
},
{
  name: "I_KIKO_03",
  url: "./sounds/INTERVIEWS/I_KIKO_03.mp3",
  duration: 175,
  author: "KIKO",
  form: "interview",
  placement: ["middle"],
  length: "long",
  language: "verbal",
  sentiment: "moderate",
  tags: ["sound", "wellness"],
  backgroundMusic: "KIKO",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_KIKO.mp3",
},
{
  name: "I_LOUELLA_01",
  url: "./sounds/INTERVIEWS/I_LOUELLA_01.mp3",
  duration: 238,
  author: "LOUELLA",
  form: "interview",
  placement: ["middle"],
  length: "long",
  language: "verbal",
  sentiment: "moderate",
  tags: ["sound", "wellness", "informative", "nature"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_LOUELLA.mp3",
},
{
  name: "I_LOUELLA_02",
  url: "./sounds/INTERVIEWS/I_LOUELLA_02.mp3",
  duration: 140,
  author: "LOUELLA",
  form: "interview",
  placement: ["middle"],
  length: "medium",
  language: "verbal",
  sentiment: "moderate",
  tags: ["Nature", "Home", "wellness"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_LOUELLA.mp3",
},
{
  name: "I_LOUELLA_03",
  url: "./sounds/INTERVIEWS/I_LOUELLA_03.mp3",
  duration: 198,
  author: "LOUELLA",
  form: "interview",
  placement: ["middle"],
  length: "long",
  language: "verbal",
  sentiment: "moderate",
  tags: ["wellness", "Nature", "informative"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_LOUELLA.mp3",
},
{
  name: "I_SAM_01",
  url: "./sounds/INTERVIEWS/I_SAM_01.mp3",
  duration: 138,
  author: "SAM",
  form: "interview",
  placement: ["middle"],
  length: "medium",
  language: "verbal",
  sentiment: "light",
  tags: ["Nature", "informative"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_SAM.mp3",
},
{
  name: "S_BIRDS_01",
  url: "./sounds/SHORTS/S_BIRDS_01.mp3",
  duration: 97,
  author: "PIERREELLIOTT",
  form: "Short",
  placement: ["middle"],
  length: "short",
  language: "NonHuman",
  sentiment: "light",
  tags: ["Nature", "sound"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_PIERREELLIOTT.mp3",
},
{
  name: "S_BIRDS_02",
  url: "./sounds/SHORTS/S_BIRDS_02.mp3",
  duration: 84,
  author: "PIERREELLIOTT",
  form: "Short",
  placement: ["middle"],
  length: "short",
  language: "NonHuman",
  sentiment: "light",
  tags: ["Nature", "sound"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_PIERREELLIOTT.mp3",
},
{
  name: "S_BIRDS_03",
  url: "./sounds/SHORTS/S_BIRDS_03.mp3",
  duration: 72,
  author: "PIERREELLIOTT",
  form: "Short",
  placement: ["middle"],
  length: "short",
  language: "NonHuman",
  sentiment: "light",
  tags: ["Nature", "sound"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_PIERREELLIOTT.mp3",
},
{
  name: "S_BIRDS_04",
  url: "./sounds/SHORTS/S_BIRDS_04.mp3",
  duration: 60,
  author: "PIERREELLIOTT",
  form: "Short",
  placement: ["middle"],
  length: "short",
  language: "NonHuman",
  sentiment: "light",
  tags: ["Nature", "sound"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_PIERREELLIOTT.mp3",
},
{
  name: "S_BIRDS_05",
  url: "./sounds/SHORTS/S_BIRDS_05.mp3",
  duration: 67,
  author: "PIERREELLIOTT",
  form: "Short",
  placement: ["middle"],
  length: "short",
  language: "NonHuman",
  sentiment: "light",
  tags: ["Nature", "sound"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_PIERREELLIOTT.mp3",
},
{
  name: "S_BIRDS_06",
  url: "./sounds/SHORTS/S_BIRDS_06.mp3",
  duration: 89,
  author: "PIERREELLIOTT",
  form: "Short",
  placement: ["middle"],
  length: "short",
  language: "NonHuman",
  sentiment: "light",
  tags: ["Nature", "sound"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_PIERREELLIOTT.mp3",
},
{
  name: "S_BIRDS_07",
  url: "./sounds/SHORTS/S_BIRDS_07.mp3",
  duration: 92,
  author: "PIERREELLIOTT",
  form: "Short",
  placement: ["middle"],
  length: "short",
  language: "NonHuman",
  sentiment: "light",
  tags: ["Nature", "sound"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_PIERREELLIOTT.mp3",
},
{
  name: "S_BIRDS_08",
  url: "./sounds/SHORTS/S_BIRDS_08.mp3",
  duration: 57,
  author: "PIERREELLIOTT",
  form: "Short",
  placement: ["middle"],
  length: "short",
  language: "NonHuman",
  sentiment: "light",
  tags: ["Nature", "sound"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_PIERREELLIOTT.mp3",
},
{
  name: "S_BIRDS_09",
  url: "./sounds/SHORTS/S_BIRDS_09.mp3",
  duration: 46,
  author: "PIERREELLIOTT",
  form: "Short",
  placement: ["middle"],
  length: "short",
  language: "NonHuman",
  sentiment: "light",
  tags: ["Nature", "sound"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_PIERREELLIOTT.mp3",
},
{
  name: "S_BIRDS_10",
  url: "./sounds/SHORTS/S_BIRDS_10.mp3",
  duration: 66,
  author: "PIERREELLIOTT",
  form: "Short",
  placement: ["middle"],
  length: "short",
  language: "NonHuman",
  sentiment: "light",
  tags: ["Nature", "sound"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_PIERREELLIOTT.mp3",
},
{
  name: "S_BIRDS_11",
  url: "./sounds/SHORTS/S_BIRDS_11.mp3",
  duration: 42,
  author: "PIERREELLIOTT",
  form: "Short",
  placement: ["middle"],
  length: "short",
  language: "NonHuman",
  sentiment: "light",
  tags: ["Nature", "sound"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_PIERREELLIOTT.mp3",
},
{
  name: "S_BIRDS_12",
  url: "./sounds/SHORTS/S_BIRDS_12.mp3",
  duration: 32,
  author: "PIERREELLIOTT",
  form: "Short",
  placement: ["middle"],
  length: "short",
  language: "NonHuman",
  sentiment: "light",
  tags: ["Nature", "sound"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_PIERREELLIOTT.mp3",
},
{
  name: "S_BIRDS_13",
  url: "./sounds/SHORTS/S_BIRDS_13.mp3",
  duration: 56,
  author: "PIERREELLIOTT",
  form: "Short",
  placement: ["middle"],
  length: "short",
  language: "NonHuman",
  sentiment: "light",
  tags: ["Nature", "sound"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_PIERREELLIOTT.mp3",
},
{
  name: "S_BIRDS_14",
  url: "./sounds/SHORTS/S_BIRDS_14.mp3",
  duration: 73,
  author: "PIERREELLIOTT",
  form: "Short",
  placement: ["middle"],
  length: "short",
  language: "NonHuman",
  sentiment: "light",
  tags: ["Nature", "sound"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_PIERREELLIOTT.mp3",
},
{
  name: "S_BIRDS_15",
  url: "./sounds/SHORTS/S_BIRDS_15.mp3",
  duration: 36,
  author: "PIERREELLIOTT",
  form: "Short",
  placement: ["middle"],
  length: "short",
  language: "NonHuman",
  sentiment: "light",
  tags: ["Nature", "sound"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_PIERREELLIOTT.mp3",
},
{
  name: "S_BIRDS_16",
  url: "./sounds/SHORTS/S_BIRDS_16.mp3",
  duration: 33,
  author: "PIERREELLIOTT",
  form: "Short",
  placement: ["middle"],
  length: "short",
  language: "NonHuman",
  sentiment: "light",
  tags: ["Nature", "sound"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_PIERREELLIOTT.mp3",
},
{
  name: "S_BIRDS_17",
  url: "./sounds/SHORTS/S_BIRDS_17.mp3",
  duration: 64,
  author: "PIERREELLIOTT",
  form: "Short",
  placement: ["middle"],
  length: "short",
  language: "NonHuman",
  sentiment: "light",
  tags: ["Nature", "sound"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_PIERREELLIOTT.mp3",
},
{
  name: "S_BIRDS_18",
  url: "./sounds/SHORTS/S_BIRDS_18.mp3",
  duration: 63,
  author: "PIERREELLIOTT",
  form: "Short",
  placement: ["middle"],
  length: "short",
  language: "NonHuman",
  sentiment: "light",
  tags: ["Nature", "sound"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_PIERREELLIOTT.mp3",
},
{
  name: "S_CHARLOTTE_01",
  url: "./sounds/SHORTS/S_CHARLOTTE_01.mp3",
  duration: 75,
  author: "CHARLOTTE",
  form: "Short",
  placement: ["end"],
  length: "medium",
  language: "verbal",
  sentiment: "moderate",
  tags: ["Nature", "wellness", "sound"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_CHARLOTTE.mp3",
},
{
  name: "S_CHARLOTTE_02",
  url: "./sounds/SHORTS/S_CHARLOTTE_02.mp3",
  duration: 25,
  author: "CHARLOTTE",
  form: "Short",
  placement: ["beginning", "middle"],
  length: "short",
  language: "verbal",
  sentiment: "light",
  tags: ["nature"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_CHARLOTTE.mp3",
},
{
  name: "S_CHARLOTTE_03",
  url: "./sounds/SHORTS/S_CHARLOTTE_03.mp3",
  duration: 32,
  author: "CHARLOTTE",
  form: "Short",
  placement: ["middle"],
  length: "short",
  language: "verbal",
  sentiment: "light",
  tags: ["nature"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_CHARLOTTE.mp3",
},
{
  name: "S_CHARLOTTE_07",
  url: "./sounds/SHORTS/S_CHARLOTTE_07.mp3",
  duration: 41,
  author: "CHARLOTTE",
  form: "Short",
  placement: ["middle"],
  length: "short",
  language: "verbal",
  sentiment: "light",
  tags: ["nature"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_CHARLOTTE.mp3",
},
{
  name: "S_CHARLOTTE_09",
  url: "./sounds/SHORTS/S_CHARLOTTE_09.mp3",
  duration: 23,
  author: "CHARLOTTE",
  form: "Short",
  placement: ["middle"],
  length: "short",
  language: "verbal",
  sentiment: "light",
  tags: ["nature"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_CHARLOTTE.mp3",
},
{
  name: "S_DEMI_14",
  url: "./sounds/SHORTS/S_DEMI_14.mp3",
  duration: 15,
  author: "DEMETRI",
  form: "Short",
  placement: ["middle", "end"],
  length: "short",
  language: "musical",
  sentiment: "light",
  tags: ["sound", "home"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_DEMETRI.mp3",
},
{
  name: "S_DEMI_15",
  url: "./sounds/SHORTS/S_DEMI_15.mp3",
  duration: 11,
  author: "DEMETRI",
  form: "Short",
  placement: ["middle", "end"],
  length: "short",
  language: "musical",
  sentiment: "light",
  tags: ["sound", "home"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_DEMETRI.mp3",
},
{
  name: "S_DEMI_16",
  url: "./sounds/SHORTS/S_DEMI_16.mp3",
  duration: 23,
  author: "DEMETRI",
  form: "Short",
  placement: ["middle", "end"],
  length: "short",
  language: "musical",
  sentiment: "light",
  tags: ["sound", "home"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_DEMETRI.mp3",
},
{
  name: "S_DEMI_17",
  url: "./sounds/SHORTS/S_DEMI_17.mp3",
  duration: 11,
  author: "DEMETRI",
  form: "Short",
  placement: ["middle", "end"],
  length: "short",
  language: "musical",
  sentiment: "light",
  tags: ["sound", "home"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_DEMETRI.mp3",
},
{
  name: "S_DEMI_18",
  url: "./sounds/SHORTS/S_DEMI_18.mp3",
  duration: 22,
  author: "DEMETRI",
  form: "Short",
  placement: ["middle", "end"],
  length: "short",
  language: "musical",
  sentiment: "light",
  tags: ["sound", "home"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_DEMETRI.mp3",
},
{
  name: "S_DEMI_19",
  url: "./sounds/SHORTS/S_DEMI_19.mp3",
  duration: 15,
  author: "DEMETRI",
  form: "Short",
  placement: ["middle", "end"],
  length: "short",
  language: "musical",
  sentiment: "light",
  tags: ["sound", "home"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_DEMETRI.mp3",
},
{
  name: "S_DEMI_20",
  url: "./sounds/SHORTS/S_DEMI_20.mp3",
  duration: 23,
  author: "DEMETRI",
  form: "Short",
  placement: ["middle", "end"],
  length: "short",
  language: "musical",
  sentiment: "light",
  tags: ["sound", "home"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_DEMETRI.mp3",
},
{
  name: "S_DEMI_21",
  url: "./sounds/SHORTS/S_DEMI_21.mp3",
  duration: 11,
  author: "DEMETRI",
  form: "Short",
  placement: ["middle", "end"],
  length: "short",
  language: "musical",
  sentiment: "light",
  tags: ["sound", "home"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_DEMETRI.mp3",
},
{
  name: "S_DEMI_22",
  url: "./sounds/SHORTS/S_DEMI_22.mp3",
  duration: 22,
  author: "DEMETRI",
  form: "Short",
  placement: ["middle", "end"],
  length: "short",
  language: "musical",
  sentiment: "light",
  tags: ["sound", "home"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_DEMETRI.mp3",
},
{
  name: "S_DEMI_23",
  url: "./sounds/SHORTS/S_DEMI_23.mp3",
  duration: 22,
  author: "DEMETRI",
  form: "Short",
  placement: ["middle", "end"],
  length: "short",
  language: "musical",
  sentiment: "light",
  tags: ["sound", "home"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_DEMETRI.mp3",
},
{
  name: "S_KIKO_B_04",
  url: "./sounds/SHORTS/S_KIKO_B_04.mp3",
  duration: 21,
  author: "KIKO",
  form: "Short",
  placement: ["middle"],
  length: "short",
  language: "musical",
  sentiment: "moderate",
  tags: ["sound", "wellness"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_KIKO.mp3",
},
{
  name: "S_KIKO_C_01",
  url: "./sounds/SHORTS/S_KIKO_C_01.mp3",
  duration: 55,
  author: "KIKO",
  form: "Short",
  placement: ["middle"],
  length: "short",
  language: "musical",
  sentiment: "moderate",
  tags: ["sound", "wellness"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_KIKO.mp3",
},
{
  name: "S_KIKO_C_02",
  url: "./sounds/SHORTS/S_KIKO_C_02.mp3",
  duration: 38,
  author: "KIKO",
  form: "Short",
  placement: ["middle"],
  length: "short",
  language: "musical",
  sentiment: "moderate",
  tags: ["sound", "wellness"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_KIKO.mp3",
},
{
  name: "S_KIKO_C_09",
  url: "./sounds/SHORTS/S_KIKO_C_09.mp3",
  duration: 41,
  author: "KIKO",
  form: "Short",
  placement: ["middle"],
  length: "short",
  language: "musical",
  sentiment: "moderate",
  tags: ["sound", "wellness"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_KIKO.mp3",
},
{
  name: "S_KIKO_S_02",
  url: "./sounds/SHORTS/S_KIKO_S_02.mp3",
  duration: 29,
  author: "KIKO",
  form: "Short",
  placement: ["middle"],
  length: "short",
  language: "musical",
  sentiment: "moderate",
  tags: ["sound", "wellness"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_KIKO.mp3",
},
{
  name: "S_KIKO_S_03",
  url: "./sounds/SHORTS/S_KIKO_S_03.mp3",
  duration: 37,
  author: "KIKO",
  form: "Short",
  placement: ["middle"],
  length: "short",
  language: "musical",
  sentiment: "moderate",
  tags: ["sound", "wellness"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_KIKO.mp3",
},
{
  name: "S_KIKO_S_04",
  url: "./sounds/SHORTS/S_KIKO_S_04.mp3",
  duration: 37,
  author: "KIKO",
  form: "Short",
  placement: ["middle"],
  length: "short",
  language: "musical",
  sentiment: "moderate",
  tags: ["sound", "wellness"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_KIKO.mp3",
},
{
  name: "S_LAUGHING_01",
  url: "./sounds/SHORTS/S_LAUGHING_01.mp3",
  duration: 16,
  author: "BABIES",
  form: "Short",
  placement: ["middle"],
  length: "short",
  language: "nonVerbal",
  sentiment: "light",
  tags: ["sound", "wellness"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_BABIES.mp3",
},
{
  name: "S_LAUGHING_02",
  url: "./sounds/SHORTS/S_LAUGHING_02.mp3",
  duration: 28,
  author: "BABIES",
  form: "Short",
  placement: ["middle"],
  length: "short",
  language: "nonVerbal",
  sentiment: "light",
  tags: ["sound", "wellness"],
  backgroundMusic: "",
  credit: "./sounds/XX_OUTRO/NAMES/NAMES_BABIES.mp3",
},
  {
      name: "M_TURKWAZ_06",
      url: "./sounds/Music/M_TURKWAZ_06.mp3",
      duration: 0,
      author: "TURKWAZ",
      form: "music",
      placement: ["middle", "end"],
      length: "long",
      language: "verbal",
      sentiment: "light",
      tags: ["sound", "Nature", "Home"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_TURKWAZ.mp3",
    },
  {
      name: "M_TURKWAZ_07",
      url: "./sounds/Music/M_TURKWAZ_07.mp3",
      duration: 0,
      author: "TURKWAZ",
      form: "music",
      placement: ["middle"],
      length: "long",
      language: "verbal",
      sentiment: "light",
      tags: ["sound", "home"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_TURKWAZ.mp3",
    },
  {
      name: "M_TURKWAZ_08",
      url: "./sounds/Music/M_TURKWAZ_08.mp3",
      duration: 0,
      author: "TURKWAZ",
      form: "music",
      placement: ["middle"],
      length: "long",
      language: "verbal",
      sentiment: "light",
      tags: ["sound", "home"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_TURKWAZ.mp3",
    },
  {
      name: "M_DEMI_01",
      url: "./sounds/Music/M_DEMI_01.mp3",
      duration: 0,
      author: "DEMETRI",
      form: "music",
      placement: ["middle"],
      length: "medium",
      language: "nonVerbal",
      sentiment: "moderate",
      tags: ["sound", "home"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_DEMETRI.mp3",
    },
  {
      name: "M_DEMI_04",
      url: "./sounds/Music/M_DEMI_04.mp3",
      duration: 0,
      author: "DEMETRI",
      form: "music",
      placement: ["middle"],
      length: "short",
      language: "nonVerbal",
      sentiment: "moderate",
      tags: ["sound", "home"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_DEMETRI.mp3",
    },
  {
      name: "M_DEMI_07",
      url: "./sounds/Music/M_DEMI_07.mp3",
      duration: 0,
      author: "DEMETRI",
      form: "music",
      placement: ["middle"],
      length: "medim",
      language: "nonVerbal",
      sentiment: "moderate",
      tags: ["sound", "home"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_DEMETRI.mp3",
    },
  {
      name: "M_DEMI_09",
      url: "./sounds/Music/M_DEMI_09.mp3",
      duration: 0,
      author: "DEMETRI",
      form: "music",
      placement: ["middle, beginning"],
      length: "short",
      language: "nonVerbal",
      sentiment: "moderate",
      tags: ["sound", "home"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_DEMETRI.mp3",
    },
  {
      name: "M_DEMI_10",
      url: "./sounds/Music/M_DEMI_10.mp3",
      duration: 0,
      author: "DEMETRI",
      form: "music",
      placement: ["middle, beginning"],
      length: "shot",
      language: "nonVerbal",
      sentiment: "moderate",
      tags: ["sound", "home"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_DEMETRI.mp3",
    },
  {
      name: "M_DEMI_12",
      url: "./sounds/Music/M_DEMI_12.mp3",
      duration: 0,
      author: "DEMETRI",
      form: "music",
      placement: ["middle, beginning"],
      length: "short",
      language: "nonVerbal",
      sentiment: "moderate",
      tags: ["sound", "home"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_DEMETRI.mp3",
    },
  {
      name: "S_JESSE_01",
      url: "./sounds/Music/S_JESSE_01.mp3",
      duration: 0,
      author: "JESSE",
      form: "music",
      placement: ["middle"],
      length: "short",
      language: "nonVerbal",
      sentiment: "light",
      tags: ["sound", "nature"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_JESSE.mp3",
    },
  {
      name: "M_JESSE_02",
      url: "./sounds/Music/M_JESSE_02.mp3",
      duration: 0,
      author: "JESSE",
      form: "music",
      placement: ["middle"],
      length: "medium",
      language: "nonVerbal",
      sentiment: "moderate",
      tags: ["sound", "nature"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_JESSE.mp3",
    },
  {
      name: "M_JESSE_05",
      url: "./sounds/Music/M_JESSE_05.mp3",
      duration: 0,
      author: "JESSE",
      form: "music",
      placement: ["middle"],
      length: "medium",
      language: "nonVerbal",
      sentiment: "heavy",
      tags: ["sound", "nature"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_JESSE.mp3",
    },
  {
      name: "M_JESSE_06",
      url: "./sounds/Music/M_JESSE_06.mp3",
      duration: 0,
      author: "JESSE",
      form: "music",
      placement: ["middle"],
      length: "medium",
      language: "nonVerbal",
      sentiment: "heavy",
      tags: ["sound", "nature"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_JESSE.mp3",
    },
  {
      name: "M_JESSE_07",
      url: "./sounds/Music/M_JESSE_07.mp3",
      duration: 0,
      author: "JESSE",
      form: "music",
      placement: ["middle"],
      length: "medium",
      language: "nonVerbal",
      sentiment: "heavy",
      tags: ["sound", "nature"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_JESSE.mp3",
    },
  {
      name: "M_JESSE_09",
      url: "./sounds/Music/M_JESSE_09.mp3",
      duration: 0,
      author: "JESSE",
      form: "music",
      placement: ["middle"],
      length: "medium",
      language: "nonVerbal",
      sentiment: "heavy",
      tags: ["sound", "nature"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_JESSE.mp3",
    },
  {
      name: "I_DIANA_01",
      url: "./sounds/Interview/I_DIANA_01.mp3",
      duration: 0,
      author: "DIANA",
      form: "interview",
      placement: ["middle, beginning"],
      length: "long",
      language: "verbal",
      sentiment: "moderate",
      tags: ["sound", "Home", "wellness", "informative"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_DIANA.mp3",
    },
  {
      name: "I_DIANA_02",
      url: "./sounds/Interview/I_DIANA_02.mp3",
      duration: 0,
      author: "DIANA",
      form: "interview",
      placement: ["middle"],
      length: "long",
      language: "verbal",
      sentiment: "moderate",
      tags: ["Nature", "wellness", "informative"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_DIANA.mp3",
    },
  {
      name: "I_DIANA_03",
      url: "./sounds/Interview/I_DIANA_03.mp3",
      duration: 0,
      author: "DIANA",
      form: "interview",
      placement: ["middle"],
      length: "long",
      language: "verbal",
      sentiment: "heavy",
      tags: ["Home", "wellness", "nature"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_DIANA.mp3",
    },
  {
      name: "I_DIANA_04",
      url: "./sounds/Interview/I_DIANA_04.mp3",
      duration: 0,
      author: "DIANA",
      form: "interview",
      placement: ["middle"],
      length: "medium",
      language: "verbal",
      sentiment: "heavy",
      tags: ["Nature", "wellness"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_DIANA.mp3",
    },
  {
      name: "I_FIDES_01",
      url: "./sounds/Interview/I_FIDES_01.mp3",
      duration: 0,
      author: "FIDES",
      form: "interview",
      placement: ["middle "],
      length: "long",
      language: "verbal",
      sentiment: "moderate",
      tags: ["sound", "wellness", "informative"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_FIDES.mp3",
    },
  {
      name: "I_FIDES_03",
      url: "./sounds/Interview/I_FIDES_03.mp3",
      duration: 0,
      author: "FIDES",
      form: "interview",
      placement: ["middle "],
      length: "medium",
      language: "verbal",
      sentiment: "moderate",
      tags: ["sound", "wellness", "informative"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_FIDES.mp3",
    },
  {
      name: "I_FIDES_04",
      url: "./sounds/Interview/I_FIDES_04.mp3",
      duration: 0,
      author: "FIDES",
      form: "interview",
      placement: ["middle "],
      length: "medium",
      language: "verbal",
      sentiment: "heavy",
      tags: ["sound", "wellness", "informative"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_FIDES.mp3",
    },
  {
      name: "M_CARMEL_01",
      url: "./sounds/Music/M_CARMEL_01.mp3",
      duration: 0,
      author: "CARMELPATRICIA",
      form: "music",
      placement: ["middle"],
      length: "long",
      language: "verbal",
      sentiment: "heavy",
      tags: ["Nature", "wellness", "Home", "sound"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_CARMELPATRICIA.mp3",
    },
  {
      name: "M_THUNDERBIRD_01",
      url: "./sounds/Music/M_THUNDERBIRD_01.mp3",
      duration: 0,
      author: "THUNDERBIRD",
      form: "music",
      placement: ["middle", "end"],
      length: "medium",
      language: "verbal",
      sentiment: "moderate",
      tags: ["sound", "wellness", "nature"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_THUNDERBIRD.mp3",
    },
  {
      name: "M_THUNDERBIRD_02",
      url: "./sounds/Music/M_THUNDERBIRD_02.mp3",
      duration: 0,
      author: "THUNDERBIRD",
      form: "music",
      placement: ["middle", "end"],
      length: "medium",
      language: "verbal",
      sentiment: "moderate",
      tags: ["sound", "wellness", "nature"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_THUNDERBIRD.mp3",
    },
  {
      name: "M_THUNDERBIRD_03",
      url: "./sounds/Music/M_THUNDERBIRD_03.mp3",
      duration: 0,
      author: "THUNDERBIRD",
      form: "music",
      placement: ["middle"],
      length: "long",
      language: "verbal",
      sentiment: "moderate",
      tags: ["sound", "wellness", "nature"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_THUNDERBIRD.mp3",
    },
  {
      name: "M_THUNDERBIRD_04",
      url: "./sounds/Music/M_THUNDERBIRD_04.mp3",
      duration: 0,
      author: "THUNDERBIRD",
      form: "music",
      placement: ["middle", "end"],
      length: "medium",
      language: "verbal",
      sentiment: "moderate",
      tags: ["sound", "wellness", "nature"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_THUNDERBIRD.mp3",
    },
  {
      name: "M_THUNDERBIRD_05",
      url: "./sounds/Music/M_THUNDERBIRD_05.mp3",
      duration: 0,
      author: "THUNDERBIRD",
      form: "music",
      placement: ["middle"],
      length: "medium",
      language: "verbal",
      sentiment: "moderate",
      tags: ["sound", "wellness", "nature"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_THUNDERBIRD.mp3",
    },
  {
      name: "M_THUNDERBIRD_06",
      url: "./sounds/Music/M_THUNDERBIRD_06.mp3",
      duration: 0,
      author: "THUNDERBIRD",
      form: "music",
      placement: ["middle "],
      length: "long",
      language: "verbal",
      sentiment: "moderate",
      tags: ["sound", "wellness", "nature"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_THUNDERBIRD.mp3",
    },
  {
      name: "M_THUNDERBIRD_07",
      url: "./sounds/Music/M_THUNDERBIRD_07.mp3",
      duration: 0,
      author: "THUNDERBIRD",
      form: "music",
      placement: ["middle"],
      length: "medium",
      language: "verbal",
      sentiment: "moderate",
      tags: ["sound", "wellness", "nature"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_THUNDERBIRD.mp3",
    },
  {
      name: "I_ELLEN_06",
      url: "./sounds/Interview/I_ELLEN_06.mp3",
      duration: 0,
      author: "ELLEN",
      form: "interview",
      placement: ["middle"],
      length: "long",
      language: "verbal",
      sentiment: "moderate",
      tags: ["Nature", "sound"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_ELLEN.mp3",
    },
  {
      name: "I_ELLEN_07",
      url: "./sounds/Interview/I_ELLEN_07.mp3",
      duration: 0,
      author: "ELLEN",
      form: "interview",
      placement: ["middle"],
      length: "medium",
      language: "verbal",
      sentiment: "moderate",
      tags: ["Nature", "sound"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_ELLEN.mp3",
    },
  {
      name: "I_ELLEN_08",
      url: "./sounds/Interview/I_ELLEN_08.mp3",
      duration: 0,
      author: "ELLEN",
      form: "interview",
      placement: ["middle"],
      length: "medium",
      language: "verbal",
      sentiment: "moderate",
      tags: ["sound"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_ELLEN.mp3",
    },
  {
      name: "I_ELLEN_09",
      url: "./sounds/Interview/I_ELLEN_09.mp3",
      duration: 0,
      author: "ELLEN",
      form: "interview",
      placement: ["middle"],
      length: "medium",
      language: "verbal",
      sentiment: "moderate",
      tags: ["sound"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_ELLEN.mp3",
    },
  {
      name: "I_ELLEN_10",
      url: "./sounds/Interview/I_ELLEN_10.mp3",
      duration: 0,
      author: "ELLEN",
      form: "interview",
      placement: ["middle", "beginning"],
      length: "medium",
      language: "verbal",
      sentiment: "moderate",
      tags: ["sound"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_ELLEN.mp3",
    },
  {
      name: "I_ELLEN_11",
      url: "./sounds/Interview/I_ELLEN_11.mp3",
      duration: 0,
      author: "ELLEN",
      form: "interview",
      placement: ["middle"],
      length: "medium",
      language: "verbal",
      sentiment: "light",
      tags: ["sound"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_ELLEN.mp3",
    },
  {
      name: "I_ELLEN_12",
      url: "./sounds/Interview/I_ELLEN_12.mp3",
      duration: 0,
      author: "ELLEN",
      form: "interview",
      placement: ["middle"],
      length: "long",
      language: "verbal",
      sentiment: "moderate",
      tags: ["sound", "wellness", "informative"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_ELLEN.mp3",
    },
  {
      name: "I_AMY_01",
      url: "./sounds/Interview/I_AMY_01.mp3",
      duration: 0,
      author: "AMY",
      form: "interview",
      placement: ["middle"],
      length: "medium",
      language: "verbal",
      sentiment: "light",
      tags: ["Nature", "informative"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_AMY.mp3",
    },
  {
      name: "I_JAYNE_04",
      url: "./sounds/Interview/I_JAYNE_04.mp3",
      duration: 0,
      author: "JAYNE",
      form: "interview",
      placement: ["middle"],
      length: "medium",
      language: "verbal",
      sentiment: "light",
      tags: ["Nature", "sound", "informative"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_JAYNE.mp3",
    },
  {
      name: "I_JAYNE_05",
      url: "./sounds/Interview/I_JAYNE_05.mp3",
      duration: 0,
      author: "JAYNE, RACHEL",
      form: "interview",
      placement: ["middle", "end"],
      length: "medium",
      language: "verbal",
      sentiment: "light",
      tags: ["Nature", "sound", "informative"],
      backgroundMusic: "DEMETRI",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_JAYNE, RACHEL.mp3",
    },
  {
      name: "I_JAYNE_07",
      url: "./sounds/Interview/I_JAYNE_07.mp3",
      duration: 0,
      author: "JAYNE",
      form: "interview",
      placement: ["middle"],
      length: "medium",
      language: "verbal",
      sentiment: "light",
      tags: ["Nature", "sound", "informative"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_JAYNE.mp3",
    },
  {
      name: "I_WRAY_01",
      url: "./sounds/Interview/I_WRAY_01.mp3",
      duration: 0,
      author: "WRAY",
      form: "interview",
      placement: ["middle"],
      length: "medium",
      language: "verbal",
      sentiment: "light",
      tags: ["informative"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_WRAY.mp3",
    },
  {
      name: "I_KIM_01",
      url: "./sounds/Interview/I_KIM_01.mp3",
      duration: 0,
      author: "KIM, RACHEL",
      form: "interview",
      placement: ["middle  "],
      length: "long",
      language: "verbal",
      sentiment: "light",
      tags: ["wellness", "nature"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_KIM, RACHEL .mp3",
    },
  {
      name: "S_KIM_02.1",
      url: "./sounds/Short/S_KIM_02.1.mp3",
      duration: 0,
      author: "KIM, RACHEL",
      form: "Short",
      placement: ["middle"],
      length: "short",
      language: "verbal",
      sentiment: "light",
      tags: ["nature"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_KIM, RACHEL .mp3",
    },
  {
      name: "S_KIM_02.2",
      url: "./sounds/Short/S_KIM_02.2.mp3",
      duration: 0,
      author: "KIM, RACHEL",
      form: "Short",
      placement: ["middle "],
      length: "short",
      language: "verbal",
      sentiment: "light",
      tags: ["nature"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_KIM, RACHEL .mp3",
    },
  {
      name: "I_KIM_03",
      url: "./sounds/Interview/I_KIM_03.mp3",
      duration: 0,
      author: "KIM",
      form: "interview",
      placement: ["middle"],
      length: "long",
      language: "verbal",
      sentiment: "light",
      tags: ["wellness", "informative", "nature"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_KIM.mp3",
    },
  {
      name: "I_KIM_04",
      url: "./sounds/Interview/I_KIM_04.mp3",
      duration: 0,
      author: "KIM",
      form: "interview",
      placement: ["middle"],
      length: "medium",
      language: "verbal",
      sentiment: "light",
      tags: ["wellness", "informative"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_KIM.mp3",
    },
  {
      name: "I_KIM_05",
      url: "./sounds/Interview/I_KIM_05.mp3",
      duration: 0,
      author: "KIM",
      form: "interview",
      placement: ["middle"],
      length: "long",
      language: "verbal",
      sentiment: "light",
      tags: ["wellness", "informative"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_KIM.mp3",
    },
  {
      name: "I_KIM_06",
      url: "./sounds/Interview/I_KIM_06.mp3",
      duration: 0,
      author: "KIM",
      form: "interview",
      placement: ["middle"],
      length: "long",
      language: "verbal",
      sentiment: "light",
      tags: ["wellness", "informative"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_KIM.mp3",
    },
  {
      name: "I_KIM_07",
      url: "./sounds/Interview/I_KIM_07.mp3",
      duration: 0,
      author: "KIM, RACHEL",
      form: "interview",
      placement: ["middle"],
      length: "long",
      language: "verbal",
      sentiment: "light",
      tags: ["wellness", "informative"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_KIM, RACHEL .mp3",
    },
  {
      name: "I_KIM_08",
      url: "./sounds/Interview/I_KIM_08.mp3",
      duration: 0,
      author: "KIM, RACHEL",
      form: "interview",
      placement: ["middle"],
      length: "long",
      language: "verbal",
      sentiment: "light",
      tags: ["wellness", "informative"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_KIM, RACHEL .mp3",
    },
  {
      name: "S_SARAH_01",
      url: "./sounds/Short/S_SARAH_01.mp3",
      duration: 0,
      author: "SARAH",
      form: "Short",
      placement: ["beginning", "middle"],
      length: "short",
      language: "verbal",
      sentiment: "heavy",
      tags: ["wellness"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_SARAH.mp3",
    },
  {
      name: "S_SARAH_02",
      url: "./sounds/Short/S_SARAH_02.mp3",
      duration: 0,
      author: "SARAH",
      form: "Short",
      placement: ["middle"],
      length: "medium",
      language: "verbal",
      sentiment: "heavy",
      tags: ["Nature", "wellness"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_SARAH.mp3",
    },
  {
      name: "I_SARAH_03",
      url: "./sounds/Interview/I_SARAH_03.mp3",
      duration: 0,
      author: "SARAH",
      form: "interview",
      placement: ["middle", "end"],
      length: "long",
      language: "verbal",
      sentiment: "moderate",
      tags: ["Nature", "wellness"],
      backgroundMusic: "KIKO",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_SARAH.mp3",
    },
  {
      name: "I_SARAH_04",
      url: "./sounds/Interview/I_SARAH_04.mp3",
      duration: 0,
      author: "SARAH",
      form: "interview",
      placement: ["middle", "end"],
      length: "long",
      language: "verbal",
      sentiment: "moderate",
      tags: ["Nature", "wellness"],
      backgroundMusic: "JESSE",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_SARAH.mp3",
    },
  {
      name: "I_SARAH_05",
      url: "./sounds/Interview/I_SARAH_05.mp3",
      duration: 0,
      author: "SARAH",
      form: "interview",
      placement: ["middle"],
      length: "medium",
      language: "verbal",
      sentiment: "light",
      tags: ["Nature", "wellness"],
      backgroundMusic: "JESSE",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_SARAH.mp3",
    },
  {
      name: "I_SARAH_06",
      url: "./sounds/Interview/I_SARAH_06.mp3",
      duration: 0,
      author: "SARAH",
      form: "interview",
      placement: ["middle"],
      length: "medium",
      language: "verbal",
      sentiment: "moderate",
      tags: ["Nature", "wellness"],
      backgroundMusic: "KIKO",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_SARAH.mp3",
    },
  {
      name: "I_SARAH_07",
      url: "./sounds/Interview/I_SARAH_07.mp3",
      duration: 0,
      author: "SARAH",
      form: "interview",
      placement: ["middle"],
      length: "long",
      language: "verbal",
      sentiment: "moderate",
      tags: ["Nature", "wellness", "sound"],
      backgroundMusic: "KIKO",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_SARAH.mp3",
    },
  {
      name: "M_MAR_01",
      url: "./sounds/Music/M_MAR_01.mp3",
      duration: 0,
      author: "SUTURE",
      form: "music",
      placement: ["middle", "end"],
      length: "medium",
      language: "verbal",
      sentiment: "light",
      tags: ["sound", "wellness"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_SUTURE.mp3",
    },
  {
      name: "M_MAR_02",
      url: "./sounds/Music/M_MAR_02.mp3",
      duration: 0,
      author: "SUTURE",
      form: "music",
      placement: ["middle", "end"],
      length: "medium",
      language: "verbal",
      sentiment: "light",
      tags: ["sound", "wellness"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_SUTURE.mp3",
    },
  {
      name: "M_MAR_03",
      url: "./sounds/Music/M_MAR_03.mp3",
      duration: 0,
      author: "SUTURE",
      form: "music",
      placement: ["middle", "end"],
      length: "medium",
      language: "verbal",
      sentiment: "light",
      tags: ["sound", "wellness"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_SUTURE.mp3",
    },
  {
      name: "S_MAR_04",
      url: "./sounds/Music/S_MAR_04.mp3",
      duration: 0,
      author: "SUTURE",
      form: "music",
      placement: ["middle"],
      length: "medium",
      language: "musical",
      sentiment: "heavy",
      tags: ["sound"],
      backgroundMusic: "",
      credit: "./sounds/XX_OUTRO/NAMES/NAMES_SUTURE.mp3",
    },
// {
//   name: "INTRO_2",
//   url: "./sounds/00_INTRO/INTRO_2.mp3",
//   duration: 113,
//   author: "",
//   form: "",
//   placement: [""],
//   length: "",
//   language: "",
//   sentiment: "",
//   tags: [""],
//   backgroundMusic: "",
//   credit: "",
// },
//   {
//       name: "OUTRO_2.1",
//       url: "./sounds/OUTRO_2.1 .mp3",
//       duration: 0,
//       author: "",
//       form: "",
//       placement: [""],
//       length: "",
//       language: "",
//       sentiment: "",
//       tags: [""],
//       backgroundMusic: "",
//       credit: "",
//     },
// {
//   name: "OUTRO_2.2",
//   url: "./sounds/XX_OUTRO/OUTRO_2.2.mp3",
//   duration: 6,
//   author: "",
//   form: "",
//   placement: [""],
//   length: "",
//   language: "",
//   sentiment: "",
//   tags: [""],
//   backgroundMusic: "",
//   credit: "",
// },
// {
//   name: "OUTRO_2.2_MUSIC",
//   url: "./sounds/XX_OUTRO/OUTRO_2.2_MUSIC.mp3",
//   duration: 35,
//   author: "",
//   form: "",
//   placement: [""],
//   length: "",
//   language: "",
//   sentiment: "",
//   tags: [""],
//   backgroundMusic: "",
//   credit: "",
// },
// {
//   name: "OUTRO_MusicOnly_Long",
//   url: "./sounds/XX_OUTRO/OUTRO_MusicOnly_Long.mp3",
//   duration: 113,
//   author: "",
//   form: "",
//   placement: [""],
//   length: "",
//   language: "",
//   sentiment: "",
//   tags: [""],
//   backgroundMusic: "",
//   credit: "",
// },
// {
//   name: "OUTRO_MusicOnly_Short",
//   url: "./sounds/XX_OUTRO/OUTRO_MusicOnly_Short.mp3",
//   duration: 39,
//   author: "",
//   form: "",
//   placement: [""],
//   length: "",
//   language: "",
//   sentiment: "",
//   tags: [""],
//   backgroundMusic: "",
//   credit: "",
// },
// {name: 'NAMES_ALBERT', url: './sounds/XX_OUTRO/NAMES/NAMES_ALBERT.mp3', duration: 2, author: ' ', form: '', placement: [''], length: '', language: '', sentiment: '', tags: [''], backgroundMusic: '', credit: ''},
// {name: 'NAMES_AMY', url: './sounds/XX_OUTRO/NAMES/NAMES_AMY.mp3', duration: 3, author: '', form: '', placement: [''], length: '', language: '', sentiment: '', tags: [''], backgroundMusic: '', credit: ''},
// {name: 'NAMES_CARMEL', url: './sounds/XX_OUTRO/NAMES/NAMES_CARMEL.mp3', duration: 3, author: '', form: '', placement: [''], length: '', language: '', sentiment: '', tags: [''], backgroundMusic: '', credit: ''},
// {name: 'NAMES_CHARLOTTE', url: './sounds/XX_OUTRO/NAMES/NAMES_CHARLOTTE.mp3', duration: 3, author: '', form: '', placement: [''], length: '', language: '', sentiment: '', tags: [''], backgroundMusic: '', credit: ''},
// {name: 'NAMES_ELLEN', url: './sounds/XX_OUTRO/NAMES/NAMES_ELLEN.mp3', duration: 3, author: '', form: '', placement: [''], length: '', language: '', sentiment: '', tags: [''], backgroundMusic: '', credit: ''},
// {name: 'NAMES_FIDES', url: './sounds/XX_OUTRO/NAMES/NAMES_FIDES.mp3', duration: 3, author: '', form: '', placement: [''], length: '', language: '', sentiment: '', tags: [''], backgroundMusic: '', credit: ''},
// {name: 'NAMES_JAYNE', url: './sounds/XX_OUTRO/NAMES/NAMES_JAYNE.mp3', duration: 1, author: '', form: '', placement: [''], length: '', language: '', sentiment: '', tags: [''], backgroundMusic: '', credit: ''},
// {name: 'NAMES_JESSE', url: './sounds/XX_OUTRO/NAMES/NAMES_JESSE.mp3', duration: 3, author: '', form: '', placement: [''], length: '', language: '', sentiment: '', tags: [''], backgroundMusic: '', credit: ''},
// {name: 'NAMES_KIKO', url: './sounds/XX_OUTRO/NAMES/NAMES_KIKO.mp3', duration: 3, author: '', form: '', placement: [''], length: '', language: '', sentiment: '', tags: [''], backgroundMusic: '', credit: ''},
// {name: 'NAMES_LOUELLA', url: './sounds/XX_OUTRO/NAMES/NAMES_LOUELLA.mp3', duration: 3, author: '', form: '', placement: [''], length: '', language: '', sentiment: '', tags: [''], backgroundMusic: '', credit: ''},
// {name: 'NAMES_NAMITHA', url: './sounds/XX_OUTRO/NAMES/NAMES_NAMITHA.mp3', duration: 4, author: '', form: '', placement: [''], length: '', language: '', sentiment: '', tags: [''], backgroundMusic: '', credit: ''},
// {name: 'NAMES_PIERRE', url: './sounds/XX_OUTRO/NAMES/NAMES_PIERRE.mp3', duration: 3, author: '', form: '', placement: [''], length: '', language: '', sentiment: '', tags: [''], backgroundMusic: '', credit: ''},
// {name: 'NAMES_RACHEL', url: './sounds/XX_OUTRO/NAMES/NAMES_RACHEL.mp3', duration: 2, author: '', form: '', placement: [''], length: '', language: '', sentiment: '', tags: [''], backgroundMusic: '', credit: ''},
// {name: 'NAMES_WRAY', url: './sounds/XX_OUTRO/NAMES/NAMES_WRAY.mp3', duration: 2, author: '', form: '', placement: [''], length: '', language: '', sentiment: '', tags: [''], backgroundMusic: '', credit: ''},
// {name: 'NAMES_SAM', url: './sounds/XX_OUTRO/NAMES/NAMES_SAM.mp3', duration: 3, author: '', form: '', placement: [''], length: '', language: '', sentiment: '', tags: [''], backgroundMusic: '', credit: ''},
// {name: 'NAMES_DEMETRI', url: './sounds/XX_OUTRO/NAMES/NAMES_DEMETRI.mp3', duration: 4, author: '', form: '', placement: [''], length: '', language: '', sentiment: '', tags: [''], backgroundMusic: '', credit: ''},
// {name: 'NAMES_TURKWAZ', url: './sounds/XX_OUTRO/NAMES/NAMES_TURKWAZ.mp3', duration: 3, author: '', form: '', placement: [''], length: '', language: '', sentiment: '', tags: [''], backgroundMusic: '', credit: ''},
// {name: 'NAMES_SARAH', url: './sounds/NAMES_SARAH.mp3', duration: 0, author: '', form: '', placement: [''], length: '', language: '', sentiment: '', tags: [''], backgroundMusic: '', credit: ''},
// {name: 'NAMES_DIANA', url: './sounds/NAMES_DIANA.mp3', duration: 0, author: '', form: '', placement: [''], length: '', language: '', sentiment: '', tags: [''], backgroundMusic: '', credit: ''},
// {name: 'NAMES_KIM', url: './sounds/NAMES_KIM.mp3', duration: 0, author: '', form: '', placement: [''], length: '', language: '', sentiment: '', tags: [''], backgroundMusic: '', credit: ''},
// {name: 'NAMES_ELLIOT', url: './sounds/NAMES_ELLIOT.mp3', duration: 0, author: '', form: '', placement: [''], length: '', language: '', sentiment: '', tags: [''], backgroundMusic: '', credit: ''},
// {name: 'NAMES_CARMELPATRICIA', url: './sounds//NAMES_CARMELPATRICIA.mp3', duration: 0, author: '', form: '', placement: [''], length: '', language: '', sentiment: '', tags: [''], backgroundMusic: '', credit: ''},
// {name: 'NAMES_SUTURE', url: './sounds/NAMES_SUTURE.mp3', duration: 0, author: '', form: '', placement: [''], length: '', language: '', sentiment: '', tags: [''], backgroundMusic: '', credit: ''},
// {name: 'NAMES_THUNDERBIRD', url: './sounds/NAMES_THUNDERBIRD.mp3', duration: 0, author: '', form: '', placement: [''], length: '', language: '', sentiment: '', tags: [''], backgroundMusic: '', credit: ''}

]